### ISSUE TITLE
Add underscores to the column names that have 2 works:  PI Login or Admin Login

### ISSUE THREAD

**Issue by katgit** [rcs-si/projinfo#3]
I actually would not use 2 words at all and name the columns as following:

Project
LPI
Admin
Academic
Deparment/Center
Campus
Allocation

You may need to add spaces in between to align the output.

**Comment by katgit** [comment]
Instead of simply "Allocation", use "SU_Allocation"

**Comment by picoting** [comment]
to clarify: i should rename the "allocation" column to "SU_allocation" but the value itself is correct?

**Comment by katgit** [comment]
Yes, The value is correct.
