### ISSUE TITLE
Add --academic" option

### ISSUE THREAD

**Issue by katgit** [rcs-si/projinfo#6]
Add "--academic" flag to the list of possible input flags.
In this case, there will be no value following this flag and when this option is used you just list all projects that are current and that are marked academic, their LPIs and Admin Contacts, Departments, and Campus info

**Comment by katgit** [comment]
It would be usefule to have one more column to this output - the number of users in each project

**Comment by picoting** [comment]
the --semester option currently returns all academic projects that are currently active. should i just rename it to --academic?

**Comment by katgit** [comment]
Yes, Let's rename it. And as we discussed it should not require any value.
